Cloud_run = True
Data_run_list = ['seq','mfe','evo','plfold']
Debug = False
save_model = False
Load_model = False
ITER      = 1
AVG_TF_SEED_AMOUNT = 3
Show_plots =False
Save_plots = False
Save_Results = True
Use_Test = True
